{{- if .Values.useFalcon }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nominatim.fullname" . }}-nginx-configmap
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  nginx.conf: |-
    {{- include "common.tplvalues.render" ( dict "value" .Values.nominatimUi.nginxConfiguration "context" $ ) | nindent 4 }}
{{- end }}